repos:
- repo: local
  hooks:
    - id: git-semver-bump
      name: bump version
      language: system
      entry: cargo run --bin cargo-git-semver git-semver bump --mode pep440
      pass_filenames: false
      always_run: true
    - id: git-semver-check-tags
      name: check latest tag
      language: system
      entry: cargo run --bin cargo-git-semver git-semver check-tags
      pass_filenames: false
      always_run: false
    - id: cargo-fmt
      name: cargo fmt
      entry: cargo fmt --
      language: system
      types: [rust]
      pass_filenames: false # This makes it a lot faster
    - id: cargo-check
      name: cargo check
      entry: cargo check
      language: system
      types: [rust]
      pass_filenames: false # This makes it a lot faster
