[package]
name = "git-semver"
version = "0.2.0-dev.1"

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
git2 = { version = "0.18.1", default-features = false }
regex = "1.9.6"
semver = "1.0.19"
toml = { version = "0.8.2", features = ["preserve_order"] }
